Di seguito verrà riportata una descrizione di tutti i microservizi e le configurazioni utilizzate nel sistema. Vedremo nel dettaglio le singole parti, mentre nel prossimo capitolo parleremo di come esse sono integrate una con l'altra.

include::single_microservices/DockerConfig.adoc[]

=== API Gateway

L'API Gateway funge da punto di ingresso unico per le richieste client verso i microservizi di un sistema distribuito. Questo Gateway è configurato per scoprire automaticamente i servizi registrati in *Eureka*, instradare dinamicamente le richieste e monitorare lo stato del sistema tramite metriche e health check.

==== Funzionamento
Il gateway utilizza Spring Boot e Spring Cloud Gateway per la gestione delle rotte, l'integrazione con *Eureka* per il service discovery e l'esposizione di metriche tramite *Prometheus*.

==== Configurazione `application.yml`

La configurazione del file `application.yml` definisce:

- La porta su cui il Gateway ascolta.
- Il nome del Gateway per la registrazione in Eureka.
- Il discovery dinamico delle rotte basato sui servizi registrati.
- La configurazione per l'export delle metriche e gli endpoint di health.

[source, yaml]
----
server:
  port: 8081  # Il Gateway sarà in ascolto sulla porta 8081

spring:
  application:
    name: api-gateway  # Nome del Gateway per la registrazione in Eureka

  cloud:
    gateway:
      discovery:
        locator:
          enabled: true  # Abilita il routing dinamico basato sui servizi registrati in Eureka

eureka:
  client:
    serviceUrl:
      defaultZone: http://eureka-server:8761/eureka/  # URL di Eureka per risoluzione tramite rete Docker
    registerWithEureka: true  # Il Gateway si registra su Eureka
    fetchRegistry: true       # Recupera il registro dei servizi da Eureka

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus  # Espone gli endpoint di health e metriche Prometheus

  health:
    livenessstate:
      enabled: true
    readinessstate:
      enabled: true
  prometheus:
    metrics:
      export:
        enabled: true  # Esporta le metriche per Prometheus

logging:
  level:
    org.springframework.cloud.gateway: DEBUG
----

Questa configurazione dell'API Gateway con Spring Boot e Spring Cloud offre una soluzione scalabile e monitorabile per la gestione delle richieste in un'architettura a microservizi, semplificando la comunicazione tra i componenti e migliorando la resilienza del sistema.
